### ISSUE TITLE
Can max_memory_restart for this module be changed?

### ISSUE THREAD

**Issue by Iamhere** [VeXell/pm2-prom-module#3]
I experience 
```PM2 log: [PM2][WORKER] Process 0 restarted because it exceeds --max-memory-restart value (current_memory=311926784 max_memory_limit=268435456 [octets])```
and want to increase it. Is it possible?

**Comment by VeXell** [comment]
Hello @Iamhere 
I guess you can restart module with additional parameter after installation

```
pm2 restart pm2-prom-module --max-memory-restart=1000M
```

Let me know if it works for you

**Comment by VeXell** [comment]
@Iamhere I updated package and increased `max_memory_restart` by default to `1Gb`. Also you can change it with command above. 

Besides i added a new option `app_check_interval`. You can use it to change interval to check apps and collect statistics.

```
pm2 set pm2-prom-module:app_check_interval 5000
```

**Comment by Iamhere** [comment]
Great! Thank you :)

**Comment by VeXell** [comment]
@Iamhere You are welcome. If you like my project you can to star it on the GitHub. Thank you.
