### ISSUE TITLE
Is it possible to add a pm2-prom-module:host option?

### ISSUE THREAD

**Issue by hermes-z** [VeXell/pm2-prom-module#4]
Hi,

by default the server is listening to 0.0.0.0 interface, which means that on a public instance, the endpoint will be reachable globally.

There is a pm2-prom-module:port  config value to change the port, but no pm2-prom-module:host, and on [index.ts](https://github.com/VeXell/pm2-prom-module/blob/main/index.ts#L27l) there is no host argument, so it is not possible to change it.

I can always patch the module to have it listen to 127.0.0.1 (which is what I want), but I think it would be nice to be able to modify this with a config value.

**Comment by VeXell** [comment]
@hermes-z Hello, yes, This is possible. Will do soon.

**Comment by VeXell** [comment]
@hermes-z Published a new version. Let me know if something is wrong.

```
### Version 2.3.2

-   Add new config option `hostname`. Listen address. If you want to specify, for example, `localhost`, `127.0.0.1`
-   Add new config option `unix_socket_path`. Run server on unix socket path.
```

**Comment by hermes-z** [comment]
@VeXell  That was fast! Thank you, works like a charm.
