### ISSUE TITLE
Is it possible to export the pm2 app status ?

### ISSUE THREAD

**Issue by dinkonin** [VeXell/pm2-prom-module#5]
Can we get a metric of the pm2 app status i.e. `pm2_app_status{job="XXX",app="YYY"} $STATUS`  ?

Value mapped for example "online" = 1 , "stopped" = 0, "errored" = 2 would be awesome.

**Comment by VeXell** [comment]
Hello @dinkonin 

Interesting question. But what a problem do you want to resolve with it?

**Comment by dinkonin** [comment]
Basically I monitor a server with 20+ apps ran by pm2, sometimes one of them errors out, or gets stopped accidentally by a developer and then forgotten. Ideally I would like to have an alertmanager rule for this situation and a timestamp of the exact time. It would also provide a nice overview of running/stopped apps in grafana.

**Comment by VeXell** [comment]
@dinkonin Ok, i will investigate what i can do here. But now i guess you can use `app_uptime` metric and if it changed it means something happened with the app. Also by my initial logic if app "stopped" or "errored" i will skip it in prom output.

**Comment by dinkonin** [comment]
> Also by my initial logic if app "stopped" or "errored" i will skip it in prom output.

This is exactly why `app_uptime` would not work, the app just dissapears from the metrics even tho it is still there in `pm2 list`.

**Comment by VeXell** [comment]
@dinkonin yes, make sense. But anyway, i will do it in t next 2.4.0 release

**Comment by dinkonin** [comment]
Also currently i monitor this using node_exporter text collector, but it would be awesome if it's integrated in your app

Here is the bash script that generates the .prom fie
```
#!/usr/bin/env bash

echo '# TYPE PM2Status gauge'
pm2 jlist|jq --arg jqhost "$HOST" -rc '.[]|"PM2Status{host=\""+$jqhost+"\", name=\""+.name+"\"} \(if .pm2_env.status == "online" then 0 elif . == "stopped" then 1 else 2 end)"'
```

**Comment by VeXell** [comment]
So, @dinkonin pull request is ready https://github.com/VeXell/pm2-prom-module/pull/6 . You can install locally and try it. If it works for you, i will publish it tomorrow.

**Comment by dinkonin** [comment]
@VeXell, tested it. Works perfectly. Thank you!

**Comment by VeXell** [comment]
@dinkonin ok, published new npm package. You can install it with `pm2 install` now

**Comment by VeXell** [comment]
@dinkonin I will appreciate if you star my repo on github. Thank you.
