### ISSUE TITLE
Unable to perceive limit in k8s

### ISSUE THREAD

**Issue by lework** [VeXell/pm2-prom-module#7]
In the k8s environment, cpu and memory data are obtained from the node, not the pod limit values.

**Comment by VeXell** [comment]
Hello @lework . Thank you for your request. Can you explain with an example please. We use this module in our Docker containers running on AMZ ECS cluster (same as k8s) and module request information based on CPU usage of every system pid and total free memory based on nodejs system module.

**Comment by lework** [comment]
k8s limit 
```
      resources:
        limits:
          cpu: '1'
          memory: 2Gi
        requests:
          cpu: 50m
          memory: 256Mi
```

pm2 list
```
┌────┬───────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name                  │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼───────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 1  │ test    │ default     │ 2.17.1  │ cluster │ 28       │ 2h     │ 0    │ online    │ 0%       │ 118.3mb  │ nonroot  │ disabled │
│ 2  │ test   │ default     │ 2.17.1  │ cluster │ 39       │ 2h     │ 0    │ online    │ 0%       │ 117.9mb  │ nonroot  │ disabled │
└────┴───────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
Module
┌────┬──────────────────────────────┬───────────────┬──────────┬──────────┬──────┬──────────┬──────────┬──────────┐
│ id │ module                       │ version       │ pid      │ status   │ ↺    │ cpu      │ mem      │ user     │
├────┼──────────────────────────────┼───────────────┼──────────┼──────────┼──────┼──────────┼──────────┼──────────┤
│ 0  │ pm2-prom-module              │ 2.4.1         │ 17       │ online   │ 0    │ 0%       │ 61.6mb   │ nonroot  │
```
metrics
```
# HELP pm2_free_memory Show available host free memory
# TYPE pm2_free_memory gauge
pm2_free_memory{serviceName="0"} 38616219648

# HELP pm2_cpu_count Show available CPUs count
# TYPE pm2_cpu_count gauge
pm2_cpu_count{serviceName="0"} 16
```

cpu and memory is node

**Comment by VeXell** [comment]
@lework So, what is problem - currently i use node.js system module to get available CPUs and memory. When you use docker with the module it requires some additional fixes to get the current limits which might not to work properly. So what i will do - i introduce 2 additional metrics with CPU count and memory especially for containers. It looks like it works fine with nodejs docker images it will be released in next update soon. If you use another docker images it might be also will require changes.

**Comment by VeXell** [comment]
@lework I have just published version 2.5.0 with docker support. It should show 3 additional metrics with docker limits. It works for me with nodejs docker `node:22-bullseye-slim` moreover `pm2_cpu_count` and  nodejs 22 version with `os.availableParallelism()` shows correct limit for docker.

Try it and let me know if it works or not for you. Thank you.

**Comment by lework** [comment]
@VeXell thanks,  Not available in Node.js v18.20.4  environments.

**Comment by VeXell** [comment]
@lework anyway check new version with pm2_container_cpu_count. It also should show if you allow only half cpu with docker settings. I might be change container_free_memory logic in next release.

**Comment by lework** [comment]
ok，thanks
