### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by lework** [VeXell/pm2-prom-module#8]
env: k8s cluster

memory use

![image](https://github.com/user-attachments/assets/cdbfd2f9-d81b-43a7-be52-1c11fa6e9349)

pm2 list
```
pm2 list
┌────┬───────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name                  │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼───────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 1  │ app    │ default     │ 2.17.1  │ cluster │ 28       │ 105m   │ 0    │ online    │ 0%       │ 755.4mb  │ nonroot  │ disabled │
│ 2  │ app  │ default     │ 2.17.1  │ cluster │ 35       │ 105m   │ 0    │ online    │ 0%       │ 751.7mb  │ nonroot  │ disabled │
└────┴───────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
Module
┌────┬──────────────────────────────┬───────────────┬──────────┬──────────┬──────┬──────────┬──────────┬──────────┐
│ id │ module                       │ version       │ pid      │ status   │ ↺    │ cpu      │ mem      │ user     │
├────┼──────────────────────────────┼───────────────┼──────────┼──────────┼──────┼──────────┼──────────┼──────────┤
│ 0  │ pm2-prom-module              │ 2.4.1         │ 17       │ online   │ 0    │ 0%       │ 607.4mb  │ nonroot  │
```

After closing the module, the memory no longer increases

```
Module
┌────┬──────────────────────────────┬───────────────┬──────────┬──────────┬──────┬──────────┬──────────┬──────────┐
│ id │ module                       │ version       │ pid      │ status   │ ↺    │ cpu      │ mem      │ user     │
├────┼──────────────────────────────┼───────────────┼──────────┼──────────┼──────┼──────────┼──────────┼──────────┤
│ 0  │ pm2-prom-module              │ 2.4.1         │ 0        │ stopped  │ 0    │ 0%       │ 0b       │ nonroot  │
└────┴──────────────────────────────┴───────────────┴──────────┴──────────┴──────┴──────────┴──────────┴──────────┘
```

![7319170274342](https://github.com/user-attachments/assets/2f634028-c06b-4bf5-9f51-da26db4eec45)

nodejs code:
```
const promClient = require('prom-client')
const { Counter, Histogram, Registry } = promClient
const { initMetrics } = require('pm2-prom-module-client')
const parseUrl = require('parseurl')

const registry = new Registry()
const metricsPrefix = 'nuxt_'

const collectDefaultMetrics = promClient.collectDefaultMetrics
collectDefaultMetrics({
  prefix: metricsPrefix,
  timeout: 5000,
  gcDurationBuckets: [0.001, 0.01, 0.1, 1, 2, 5],
  register: registry
})

const httpRequestsTotal = new Counter({
  name: `${metricsPrefix}http_request_total`,
  help: 'Total number of HTTP requests',
  labelNames: ['method', 'path', 'code'],
  registers: [registry]
})

const pageRenderDuration = new Histogram({
  name: `${metricsPrefix}http_request_duration_seconds`,
  help: 'Time for page response to render',
  registers: [registry],
  buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10],
  labelNames: ['path', 'code']
})

const serviceRequestDuration = new Histogram({
  name: `${metricsPrefix}service_response`,
  help: 'Time to get service response',
  registers: [registry],
  buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10],
  labelNames: ['code', 'path']
})

initMetrics(registry)

module.exports = async (req, res, next) => {
  const end = pageRenderDuration?.startTimer()
  req.serviceRequestDuration = serviceRequestDuration

  res.on('finish', () => {
    const path = parseUrl(req).pathname || '/'
    httpRequestsTotal?.inc({ method: req.method, path, code: res.statusCode })
    if (end) {
      end({ path, code: res.statusCode })
    }
    req.serviceRequestDuration = null
  })
  next()
}

```

**Comment by VeXell** [comment]
Hello @lework . Can you provide your pm2-module settings please also.

**Comment by lework** [comment]
```
pm2 conf
Module: pm2-prom-module
$ pm2 set pm2-prom-module:port 9091
$ pm2 set pm2-prom-module:hostname 0.0.0.0
$ pm2 set pm2-prom-module:unix_socket_path
$ pm2 set pm2-prom-module:service_name
$ pm2 set pm2-prom-module:debug false
$ pm2 set pm2-prom-module:aggregate_app_metrics true
$ pm2 set pm2-prom-module:app_check_interval 3000
Module: module-db-v2
$ pm2 set module-db-v2:pm2-prom-module [object Object]
```

**Comment by lework** [comment]
One idea I have is to set the maximum memory when starting the module, and when it is exceeded, pm2 will restart the module, 

for example 

`pm2 restart pm2-prom-module --max-memory-restart=3000M`

Putting this in the module configuration should minimize the impact of memory leaks.

**Comment by VeXell** [comment]
@lework This is expected behaviour of the plugin and in docker container you can setup `--max-memory-restart` when you install the plugin (this is described in the plugin README). But anyway if memory is increasing it is not proper situation. I will have a look deeper into it. Might be this is a problem with `prom-module` for nodejs.

**Comment by lework** [comment]
@VeXell  

I think I found the problem: I have an application with product detail pages, each with a different URL path, totaling about 50w 
 paths. This causes Prometheus to collect a lot of metrics information, which takes up a very large amount of memory. Therefore, it is the huge number of metrics that is causing the memory to be constantly high.

I've also run multiple pressure tests of a single product page, several product pages, and this doesn't cause the pm2-prom-module memory to go up.

I ended up categorizing all the product page paths into one PATH metric, and that solved this problem of memory increasing all the time.

Thanks for your open source contribution.

**Comment by VeXell** [comment]
@lework Thanks for you investigation. Yeah, it is better to simplify metrics in the Prometheus.

**Comment by Manfredik** [comment]
Смотрел я на эту ветку и все таки решил отписать. Память начинает утекать в определенный момент. При этом пром модуль показывает потребление 200мб процессы тоже адекватно. А вот утекает pm2-runtime процесс. При этом у него утечка 15мб в 5 сек. Отключение пром-модуля  останавливает жор памяти. Что кладет докер контейнер я искал очень долго, в том числе я делал оптимизацию по фиксированию запросов по URL оставлял только фикисрованный набор путей, а все остальное писал как other и т.п.

Жаль что вы закрыли issue а не разобрались и пофиксили.

**Comment by VeXell** [comment]
@Manfredik ну тут человек нашел у себя проблему. Скиньте ваши скрины где и как утекает и что за pm2-runtime процесс. Шлете ли вы события в pm2 из ноды и какие. Какая версия pm2. Если шлете события из ноды. Попробуйте их отключить. Будет ли утечка в этом случае? Нужно понимать на каком этапе это происходит.
